import java.util.Vector;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.Queue;
import java.util.NoSuchElementException;

import uobject.*;
import icommand.*;
import irotatable.*;
import imovable.*;
import iburnable.*;

import AutoGenerated.*;

class m {
	static double eps=0.0001;
	static Vector pos;
	static double alpha, fc, v;
	static ICommand cmd;
	
    public static void main(String[] args) throws Exception {
		Ship ship1=new Ship(1, 1, 0.0, 360, 0.0);
		//cmd=IoC.Resolve("Scopes.New", "scope1"); cmd.exec(); if(cmd!=null)System.out.println("Test15 passed\n"); else System.out.println("Test15 FAILED\n");
		//cmd=IoC.Resolve("Scopes.New", "scope2"); cmd.exec(); if(cmd!=null)System.out.println("Test26 passed\n"); else System.out.println("Test26 FAILED\n");
		IMovable ad=new AutoGenerated_MovableAdapter_IMovable(ship1);
		ad.setVelocity(2, 3);
		
		//cmd=IoC.Resolve("IoC.Register", "X1", (IFunction)((x) -> (int)x[0]+1) ); cmd.exec(); if(cmd!=null)System.out.println("Test21 passed\n"); else System.out.println("Test21 FAILED\n");
		//cmd=IoC.Resolve("X1", 1 ); cmd.exec(); if(cmd!=null)System.out.println("Test23 passed\n"); else System.out.println("Test23 FAILED\n");
    }



}


