#!/bin/bash
if [[ $1 == "build" ]] ; then
	#javac -d . ICommand/ICommand.java && javac -d . IRotatable/IRotatable.java && javac -d . IMovable/IMovable.java && javac dz2.java && java m
	#javac ICommand/ICommand.java && javac IRotatable/IRotatable.java && javac IMovable/IMovable.java && javac dz2.java && java m
	path='-cp src'
	javac $path ./src/uobject/*.java && javac $path ./src/IBurnable/*.java && javac $path ./src/ICommand/*.java && javac $path ./src/IRotatable/*.java && javac $path ./src/IMovable/*.java && javac $path ./src/AutoGenerated/*.java && javac $path ./src/Tank_Operations_IMovable/*.java

	if [ $? -eq 0 ] ; then 
		echo 'dz11' && javac $path ./src/dz11.java && java $path m
	fi

fi

if [[ $1 == "clean" ]] ; then
	rm -rf src/*.class
	rm -rf src/ICommand/*.class
	rm -rf src/IRotatable/*.class
	rm -rf src/IMovable/*.class
	rm -rf src/IBurnable/*.class
	rm -rf src/UObject/*.class
	rm -rf src/AutoGenerated/*.class
	rm -rf src/tank_operations_imovable/*.class
fi

if [[ $1 == "rebuild" ]] ; then
	bash make.sh clean
	bash make.sh build
fi
