#!/bin/bash
echo 'Hi, preprocessor is running....'

grep -i interface ./*/*.java | awk -F":" '{print $1}' | sort -r | while read fl ; do
	echo $fl
	ifName=$(cat $fl | grep -E -v "//|package |import |^$" | tr -d "\n" | sed -r 's/[;{}]/\n/g' | grep -i interface | sed -r 's/.*interface ([^ ]+).*/\1/')
	echo $ifName
	if [[ "$ifName" != *"able" ]] ; then
		echo 'Skipping...'
		continue
	fi
	ableName=$(echo "$ifName" | sed -r 's/.+\_I(.+)/\1/')
	
	#cat $fl
	#echo $ifName, $ableName
	
	className='AutoGenerated_'$ableName'Adapter'
	#classFlName=$className'.class'
	echo 'package AutoGenerated;'
	echo 'import '$ifName'.*;'
	echo 'import uobject.*;'
	echo 'import java.util.Vector;'
	echo 'import icommand.IoC;'
	echo 'class '$className' implements '$ifName' {'
	echo '	UObject obj;'
	echo '	public '$className'(UObject obj) {'
	echo '		this.obj = obj;'
	echo '	}'
	
	cat $fl | grep -E -v "//|package |import |^$" | tr -d "\n" | sed -r 's/[;{}]/\n/g' | grep "(" | grep ")" | sed -r 's/([^ ]+) (.+[^(])\(([^)]*)\).*/\1 \2 \3/' | while read return method args ; do
		#echo $return, $method, $args
		if [[ "$method" == *"get"* ]] ; then
			#echo "It's GET."
			suff=${method/get/}
			echo '	public '$return' get'$suff'() throws Exception {'
			echo '		return IoC.Resolve("'$ifName':'${suff,,}'.get", obj);'
			echo '	}'
		elif [[ "$method" == *"set"* ]] ; then
			#echo "It's SET."
			suff=${method/set/}
			#argsName=$(echo "$args" | sed -r 's/[^ ]+ +([^ ]+)/\1/')
			argsNames=$(echo $(echo "$args" | sed -r 's/,/\n/g' | sed -r 's/.+ ([^ ]+)/\1/') | sed -r 's/ /, /g')
			echo '	public '$return' set'$suff'('$args') throws Exception {'
			echo '		return IoC.Resolve("'$ifName':'${suff,,}'.set", obj, '$argsNames');'
			echo '	}'
		else 
			#echo 'Something else: '$method
			echo ''
		fi
	done
	
	echo '}'
	
	#break
done