package AutoGenerated;
import iburnable.*;
import uobject.*;
import java.util.Vector;
import icommand.IoC;
public class AutoGenerated_BurnableAdapter_IBurnable implements IBurnable {
	UObject obj;
	public AutoGenerated_BurnableAdapter_IBurnable(UObject obj) {
		System.out.println("AutoGenerated_BurnableAdapter_IBurnable: new()");
		this.obj = obj;
	}
	public void burn(){  }
	public double check(){ return(0); }
}
