package AutoGenerated;
import irotatable.*;
import uobject.*;
import java.util.Vector;
import icommand.IoC;
public class AutoGenerated_RotatableAdapter_IRotatable implements IRotatable {
	UObject obj;
	public AutoGenerated_RotatableAdapter_IRotatable(UObject obj) {
		System.out.println("AutoGenerated_RotatableAdapter_IRotatable: new()");
		this.obj = obj;
	}
	public void rotate(){  }
}
